# ./.tmuxinator.yml

name: cluster
root: /home/sebastian/Documents/Projects/distod

startup_window: dev
startup_pane: 1

windows:
  - dev:
      layout: even-horizontal
      panes:
        - sbt:
            - clear
            - sbt
        - git:
            - clear
            - git status
  - deployment:
      layout: tiled
      # Synchronize all panes of this window
      synchronize: after
      pre:
        - cd deployment
      panes:
        - odin01:
            - export host=odin01
            - ssh $host
            - clear
        - odin02:
            - export host=odin02
            - ssh $host
            - clear
        - odin03:
            - export host=odin03
            - ssh $host
            - clear
        - odin04:
            - export host=odin04
            - ssh $host
            - clear
        - odin05:
            - export host=odin05
            - ssh $host
            - clear
        - odin06:
            - export host=odin06
            - ssh $host
            - clear
        - odin07:
            - export host=odin07
            - ssh $host
            - clear
        - odin08:
            - export host=odin08
            - ssh $host
            - clear
        - thor01:
            - export host=thor01
            - ssh $host
            - clear
        - thor02:
            - export host=thor02
            - ssh $host
            - clear
        - thor03:
            - export host=thor03
            - ssh $host
            - clear
        - thor04:
            - export host=thor04
            - ssh $host
            - clear
  - monitor:
      layout: tiled
      synchronize: after
      panes:
        - odin01:
            - ssh odin01
            - htop
        - odin02:
            - ssh odin02
            - htop
        - odin03:
            - ssh odin03
            - htop
        - odin04:
            - ssh odin04
            - htop
        - odin05:
            - ssh odin05
            - htop
        - odin06:
            - ssh odin06
            - htop
        - odin07:
            - ssh odin07
            - htop
        - odin08:
            - ssh odin08
            - htop
        - thor01:
            - ssh thor01
            - htop
        - thor02:
            - ssh thor02
            - htop
        - thor03:
            - ssh thor03
            - htop
        - thor04:
            - ssh thor04
            - htop
